//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class change_info_history
    {
        public int id { get; set; }
        public System.DateTime change_time { get; set; }
        public string description { get; set; }
        public Nullable<int> room_id { get; set; }
    
        public virtual room room { get; set; }
    }
}
