//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_detail_order
    {
        public int id { get; set; }
        public Nullable<int> food_order_id { get; set; }
        public Nullable<int> food_id { get; set; }
        public Nullable<int> food_service_id { get; set; }
        public int quantity { get; set; }
        public int total_price { get; set; }
    
        public virtual food food { get; set; }
        public virtual food_order food_order { get; set; }
        public virtual food_service food_service { get; set; }
    }
}
