//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_WPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotel_management_systemEntities : DbContext
    {
        public hotel_management_systemEntities()
            : base("name=hotel_management_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<change_info_history> change_info_history { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<food_detail_order> food_detail_order { get; set; }
        public virtual DbSet<food_order> food_order { get; set; }
        public virtual DbSet<food_service> food_service { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<payment_method> payment_method { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<service_detail_order> service_detail_order { get; set; }
        public virtual DbSet<service_info> service_info { get; set; }
        public virtual DbSet<service_order> service_order { get; set; }
        public virtual DbSet<successful_reservation> successful_reservation { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<user_type> user_type { get; set; }
    }
}
