//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public System.DateTime payment_date { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> payment_method_id { get; set; }
        public string card_number { get; set; }
        public string valid_date { get; set; }
        public string account_holder { get; set; }
        public string customer_feedback { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual payment_method payment_method { get; set; }
    }
}
