//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.successful_reservation = new HashSet<successful_reservation>();
        }
    
        public int id { get; set; }
        public System.DateTime checkin_datetime { get; set; }
        public Nullable<System.DateTime> reality_checkin_datetime { get; set; }
        public System.DateTime checkout_datetime { get; set; }
        public Nullable<System.DateTime> reality_checkout_datetime { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public bool status { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<successful_reservation> successful_reservation { get; set; }
    }
}
